services:
  - type: web
    name: tulip
    runtime: go
    plan: free
    region: ohio
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    disk:
      name: data
      mountPath: /data
      sizeGB: 5
